os:
  - linux
  - osx

language: c

env:
  - BRANCH=0.19.6
  - BRANCH=0.20.2
  # This is the latest working Nim version against which Nimble is being tested
  - BRANCH=#2565d3d102efd21ba02ed1f3b96d892fe2637d2b

cache:
  directories:
    - "$HOME/.choosenim/toolchains/nim-0.19.6"
    - "$HOME/.choosenim/toolchains/nim-0.20.2"

install:
  - export CHOOSENIM_CHOOSE_VERSION=$BRANCH
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y

before_script:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - cd tests
  - nim c -r tester
  - cd ..
  - ./src/nimble install -y

notifications:
  irc: "chat.freenode.net#nimbuild"
