os:
  - linux
dist: trusty

language: c

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

install:
  - export CHOOSENIM_CHOOSE_VERSION="#7bb93c730ea87f"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y

before_script:
  - set -e
  - set -x
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - cd tests
  - nim c -r tester
  - cd ..
  - ./src/nimble install -y

notifications:
  irc: "chat.freenode.net#nimbuild"
