os:
  - windows
  - linux
  - osx

language: c

env:
  - BRANCH=0.19.6
  - BRANCH=0.20.2
  - BRANCH=1.0.6
  # This is the latest working Nim version against which Nimble is being tested
  - BRANCH=#ab525cc48abdbbbed1f772e58e9fe21474f70f07

cache:
  directories:
    - "$HOME/.nimble/bin"
    - "$HOME/.choosenim"

install:
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - cd tests
  - nim c -r tester
  - cd ..
  - ./src/nimble install -y

notifications:
  irc: "chat.freenode.net#nimbuild"
