name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        target:
          ## Uncomment whichever builds you want:
          ##   nightly:   download pre-built binaries (this is the fastest on all OSes)
          ##   release:   download official releases (binaries for linux/win, build from source on macOS)
          ##   sourcetar: download source archive and build
          ##   git:       check out a specific tag/commit/branch and build source
          - nightly:https://github.com/nim-lang/nightlies/releases/latest-version-1-0/
          - nightly:https://github.com/nim-lang/nightlies/releases/latest-version-1-2/
          - nightly:https://github.com/nim-lang/nightlies/releases/latest-version-1-4/
          - nightly:https://github.com/nim-lang/nightlies/releases/tag/2020-11-11-devel-bbe49a14ae827b6474d692042406716a3b3dd71f
          # - sourcetar:https://github.com/nim-lang/nightlies/releases/download/latest-version-1-0/source.tar.xz
          # - sourcetar:https://github.com/nim-lang/nightlies/releases/download/latest-version-1-2/source.tar.xz
          # - sourcetar:https://github.com/nim-lang/nightlies/releases/download/latest-version-1-4/source.tar.xz
          # - sourcetar:https://github.com/nim-lang/nightlies/releases/download/2020-11-11-devel-bbe49a14ae827b6474d692042406716a3b3dd71f/nim-1.5.1.tar.xz
          # - release:1.4.0
          # - release:1.2.8
          # - release:1.0.10
          # - git:devel
          # - git:bbe49a14ae827b6474d692042406716a3b3dd71f
    name: ${{ matrix.os }} - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Nim
        shell: bash
        run: bash .github/install-nim.sh ${{ matrix.target }}
      - run: nim --version
      - name: Run nim c -r tester
        run: |
          cd tests
          nim c -r tester
      - run: ./src/nimble install -y
